name: I1M-Ejercicios
version: '0.1.0.0'
synopsis: Ejercicios de I1M 2017-18
description: >
  Ejercicios de programación funcional con Haskell propuestos en la
  asignatura I1M (Informática de 1º del Grado en Matemáticas de la Universidad
  de Sevilla) durante el curso 2017-18.
category: Educational
author: Jose A. Alonso
maintainer: JoseA.Alonso@gmail.com
copyright: Jose A. Alonso
license: BSD3
github: jaalonso/I1M-Ejercicios
extra-source-files:
- README.org
dependencies:
- QuickCheck >=2.8.1
library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - base >=4.7 && <5
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hspec
    - I1M-Ejercicios
     
